services:
    metamodels.attribute_decimal.factory:
        class: MetaModels\AttributeDecimalBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }

    MetaModels\AttributeDecimalBundle\Schema\DoctrineSchemaGenerator:
        tags:
            - { name: 'metamodels.schema-generator.doctrine' }
